### ISSUE TITLE
Fix styling issues across the app

### ISSUE THREAD

**Issue by BlueishLeaf** [BlueishLeaf/open-hub#4]
## The Following areas need attention
* The stats on the small repo cards are poorly positioned
* The registration form has a misaligned field
* The small repo cards on the browse section have uneven gaps between them
* There are several fields of the incorrect type in the search component
* The popular repos are not completely centered on the page

**Comment by S00170565** [comment]
<marquee>LOOOOOOOOOOL</marquee>
